task: association

models:
  apriori:
    - min_support: 0.03
    - use_colnames: True  
    - max_len: 3
    
  association_rules: 
    - metric: confidence
    - min_threshold: 0.60    

